package com.carServices.backend.enums;

public enum ActivityLogAction {
    // SYSTEM
    LOGIN,

    // VEHICLES
    VEHICLE_CREATED,
    VEHICLE_UPDATED,
    VEHICLE_DELETED,

    // VEHICLE MAKES
    VEHICLE_MAKE_CREATED,
    VEHICLE_MAKE_UPDATED,
    VEHICLE_MAKE_DELETED,

    // VEHICLE MODELS
    VEHICLE_MODEL_CREATED,
    VEHICLE_MODEL_UPDATED,
    VEHICLE_MODEL_DELETED,

    // CLIENTS
    CLIENT_CREATED,
    CLIENT_UPDATED,
    CLIENT_DELETED,

    // MECHANICS
    MECHANIC_CREATED,
    MECHANIC_UPDATED,
    MECHANIC_DELETED,

    // REPAIRS
    REPAIR_CREATED,
    REPAIR_UPDATED,
    REPAIR_DELETED
}
