package com.carServices.backend.enums;

public enum Permission {

    // USER MANAGEMENT
    USER_CREATE,
    USER_UPDATE,
    USER_READ,
    USER_DELETE,

    // VEHICLES
    VEHICLE_CREATE,
    VEHICLE_UPDATE,
    VEHICLE_READ,
    VEHICLE_DELETE,

    // CLIENTS
    CLIENT_CREATE,
    CLIENT_UPDATE,
    CLIENT_READ,
    CLIENT_DELETE,

    // MECHANICS
    MECHANIC_CREATE,
    MECHANIC_UPDATE,
    MECHANIC_READ,
    MECHANIC_DELETE
}
