package com.ftn.backend.enums;

public enum Permission {
    SUJET_CREATE,
    SUJET_UPDATE_OWN,
    SUJET_DELETE_OWN,
    REPONSE_CREATE,
    REPONSE_UPDATE_OWN,
    REPONSE_DELETE_OWN,
    REPONSE_LIKE,
    REPONSE_SIGNALER,
    SUJET_EPINGLER,
    SUJET_FERMER,
    SUJET_DELETE_ANY,
    SUJET_UPDATE_ANY,
    REPONSE_DELETE_ANY,
    FORUM_CREATE,
    FORUM_UPDATE,
    FORUM_DELETE,
    RESERVATION_APPROVE
}
